export { Header } from "./Header"
export { NavbarMenu } from "./NavbarMenu";
export { NavItems } from "./NavItems";
export { Button } from "./Button";
export { SectionContaier } from "./SectionContaier";
export { Desplegable } from "./Desplegable";
export { QA } from "./QA";
export { Instrucciones } from "./Instrucciones";
export { BackgroundImage } from "./BackgroundImage";
export { Layout } from "./Layout";